### ISSUE TITLE
Email could not be saved.....at first

### ISSUE THREAD

**Issue by polytan02** [fmbiete/Z-Push-contrib#224] opened 2015-08-14 18:50 UTC
``BackendIMAP->saveSentMessage(): The email could not be saved to Sent Items folder. Check your configuration.``

This is the issue I ran into.

The thing is, I believe that I filed backend/imap/config.php correctly as after a little while (around 10 to 20 minutes ?) without changing the configuration the issue vanishes and I can then have the sent emails stored in the 'Sent' folder.

Would you know why it would take 10 to 20 minutes before the emails are saved and the issue stops ?

I confirm that the emails are really not saved for the first 10 to 20 minutes.

I tried to replicate this behavior, and it is what I get at each new installation of debian + complete server + z-push.

If I keep the system and just remove z-push (installed in /var/www/z-push and /var/log/z-push), reinstall it and keep the devices configured in ActiveSync, then I don't have the issue.

**Comment by fmbiete** [comment] 2015-08-16 13:36
Can you post the complete log of a process where the sent message cannot be saved?
I would think that there is an IMAP problem, and maybe the log is telling you more info in the logoff function.

**Comment by polytan02** [comment] 2015-08-16 18:42
It is a very strange bug. I think it only happens when the devices are been synchronised for the first time as it doesn't happen after a little while.

I suppose it is the time needed for z-push to build a database with the messages or something like this ? Maybe these emails could be stored to be saved later ?

**Comment by mikhail-guru** [comment] 2015-08-19 14:05
The same for me. iOS 8.4.

**Comment by fmbiete** [comment] 2015-08-21 15:19
Logs, please!
Or better yet, can you check using the docker images in the docker folder?

**Comment by mikhail-guru** [comment] 2015-08-21 15:21
Docker can't. For logs please give instructions how to enable logs, I don't see it in readme/wiki.

**Comment by fmbiete** [comment] 2015-08-21 18:45
In the main config.php you need to set the variables to this:

```
    define('LOGFILEDIR', '/var/log/z-push/');
    define('LOGFILE', LOGFILEDIR . 'z-push.log');
    define('LOGERRORFILE', LOGFILEDIR . 'z-push-error.log');
    define('LOGLEVEL', LOGLEVEL_WBXML);
```

**Comment by polytan02** [comment] 2015-08-21 18:47
Again, after a little while the bug stops so difficult to replicate.

Would there be some sort of database been created for the first ever use of z-push ?

**Comment by fmbiete** [comment] 2015-08-21 18:49
No. The state files/record are only used for the received messages, not the sent. Every send operation should be equal in conditions.

**Comment by polytan02** [comment] 2015-08-21 18:52
I'll do my best to get some logs for this issue this weekend.

**Comment by fmbiete** [comment] 2015-08-21 18:53
Thanks!!!

**Comment by mikhail-guru** [comment] 2015-08-21 19:01
@fmbiete I've sent a log file to your email. For me, I see only one important line:
BackendIMAP->getFolderIdFromImapId('SENT') = not found

**Comment by mikhail-guru** [comment] 2015-08-21 19:21
I've found the problem. In backend/imap/config.php:

// Sent folder name (case doesn't matter)
define('IMAP_FOLDER_SENT', 'SENT');

It is not true. Case is matter. Should be:
define('IMAP_FOLDER_SENT', 'Sent');

I think it just somewhere forgotten to make the string case-insensitive.

**Comment by fmbiete** [comment] 2015-08-22 16:47
Indeed, that's a bug. The referenced commit should fix it, but you will need to do a full resync. Thanks @mikhail-guru !!

@polytan02 Can you check if you have the same problem?

**Comment by mikhail-guru** [comment] 2015-08-23 13:50
Nothing changes.

**Comment by polytan02** [comment] 2015-08-23 21:56
So, I did another test : 
- New installation of my server
- installation of z-push
- emails sent from my phone ==> "emails cannot be saved"
- If then I send an email from a webmail on my server ==> It works, but I'm not using z-push

==> After that, it seems that I can have access to more folder from my phone using z-push and so I can save emails.

Would it be simplier to leave the folder blanks in backend/imap/config.php to have z-push auto discover folders ?

**Comment by mikhail-guru** [comment] 2015-08-24 19:18
Now it is not working even after replacement SENT to Sent.

**Comment by fmbiete** [comment] 2015-08-25 04:18
@mikhail-guru can you look at your logs? Search for a IMAP Logoff message for every process (or end messages). A possibility should be your php process being terminated before they can save the folder ids info to storage.

Your php max_execution_time must be at least 600 seconds.

**Comment by mikhail-guru** [comment] 2015-08-25 07:11
25/08/2015 09:09:23 [31092] [ WARN] [mikhail@emelchenkov.pro] BackendIMAP->getFolderIdFromImapId('SENT') = not initialized!
25/08/2015 09:09:23 [31092] [ERROR] [mikhail@emelchenkov.pro] BackendIMAP->saveSentMessage(): The email could not be saved to Sent Items folder. Check your configuration.

**Comment by mikhail-guru** [comment] 2015-08-25 07:13
I've saved a log of Sending process and will mail you if you need it.

**Comment by polytan02** [comment] 2015-08-25 10:02
Hi,

Thanks @fmbiete to help me sort out this issue. (external emails sent to exchange big raw logs via emails).

I sorted out my issue by modifiying my /etc/php5/fpm/poold.z-push dedicated php-fpm process as such : 

; Start a new pool named 'www'.
; the variable $pool can we used in any directive and will be replaced by the
; pool name ('www' here)
[z-push]
listen = /var/run/php5-fpm-z-push.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0600

user = www-data
group = www-data

pm = dynamic

pm.max_children = 10

pm.start_servers = 3

pm.min_spare_servers = 3

pm.max_spare_servers = 5

pm.max_requests = 0

pm.status_path = /fpm-status

ping.path = /ping

request_terminate_timeout = 700s

request_slowlog_timeout = 5s

slowlog = /var/log/nginx/z-push.slow.log

rlimit_files = 4096

rlimit_core = 0

chdir = /var/www/z-push

catch_workers_output = yes

php_value[upload_max_filesize] = 50M
php_value[post_max_size] = 50M
php_value[mail.add_x_header] = Off
php_value[max_execution_time] = 600
php_value[max_input_time] = 300
php_value[memory_limit] = 256M

**Comment by fmbiete** [comment] 2015-08-29 13:35
@mikhail-guru Have you checked if the Logoff debug line appears always?

The problem seems to be the process being terminated before it saves the states, so the SendMail execution won't have the Sent folder stored yet.

**Comment by dominicpratt** [comment] 2015-09-03 12:20
Same problem over here, foldername is written correctly (case-sensitive):

StatusException: SyncCollections->CheckForChanges(): Timeout forced after 29s from 900s due to other process - code: 3 - file: /var/www/z-push/lib/core/synccollections.php:488
[...]
03/09/2015 14:19:04 [11848] [WARN] [hallo@example.com] BackendIMAP->getFolderIdFromImapId('Gesendet') = not initialized!
03/09/2015 14:19:04 [11848] [ERROR] [hallo@example.com] BackendIMAP->saveSentMessage(): The email could not be saved to Sent Items folder. Check your configuration.

**Comment by fmbiete** [comment] 2015-09-03 15:52
@dominicpratt put your log level to WBXML and check for the Logoff line. As I have said the executions have to terminate correctly, so we all need to configure php correctly.

BTW: I will be away this month, so if I don't answer I will do it in october.

**Comment by mikhail-guru** [comment] 2015-09-07 08:40
@fmbiete I have sent you log to email.

**Comment by FrankvdAa** [comment] 2015-09-22 10:02
If I can be of any help debugging this problem, please let me know!

**Comment by meitonga** [comment] 2015-10-13 15:54
Hi,

I have probably experienced the same issue.

I found out that this happens when there is no EMail in the Sentfolder between the cutoffdate and now.

At this time I see something in the logs during provisioning like:
BackendIMAP->GetMessageList('Sent','1444146484'): 0 result for the search or error: 

The situation solves, when another EMail Client is used for sending an EMail. Then this new EMail will be saved to the Sent folder and the above message disapears.
Then sending of emaisl with z-push is possible.

**Comment by m-emelchenkov** [comment] 2015-10-13 15:59
It seems it is another issue. I never had messages sent from phone saved in Sent after last update.

**Comment by FrankvdAa** [comment] 2015-10-14 07:56
@fmbiete I've send you an email with WBXML logs, please let me know if there is anything else I can help with.

**Comment by cpitchford** [comment] 2015-10-23 23:15
I've been seeing this problem since I updated my nexus 6/9 to marshmallow. I've been suffering random sync problems with Android 6, but this is the first error I can reliably reproduce:

Enabling debug logging shows:
BackendIMAP->getFolderIdFromImapId('Sent', false) = not found

Which is strange since with debug logging enabled I also see:

BackendIMAP->getImapIdFromFolderId('xxxxxxxx') = Sent
and 
BackendIMAP->getImapIdFromFolderId('yyyyyyyy') = Sent

xxxxxxxx and yyyyyyyy are two different values, both for the same user.

Testing IMAP returns:

X LIST "" *
...
...
* LIST (\NoInferiors \UnMarked \Sent) "/" Sent
* LIST (\HasNoChildren) "/" INBOX
X OK List completed.

I'll keep playing and see what I can find

**Comment by fmbiete** [comment] 2015-11-08 11:11
I will try to answer everyone without mixing problems.

@m-emelchenkov , @meitonga 
Was your user a new account? A lot of servers don't create the Sent folder, the client must do it. BUT, Z-Push doesn't do it. Is it possible? You can check it doing the same as cpitchford did (telnet IMAP server and use the LIST command).
If that's it, please open a new issue: "Z-Push should create missing folders - configurable"

@cpitchford 
You should do a full resync of your account (use z-push-admin to remove the states). I have found that problem after updating Android versions (also with Nexus devices).

**Comment by m-emelchenkov** [comment] 2015-11-08 11:13
@fmbiete It's an existing account. It's completely broke after the last changes you pushed for fixing this issue—before that I can change the capitalization in config and it worked fine.

**Comment by fmbiete** [comment] 2015-11-08 11:28
@m-emelchenkov  Can you check with this function?

```
    protected function getFolderIdFromImapId($imapid, $case_sensitive = true) {
        $this->InitializePermanentStorage();

        if (!isset($this->permanentStorage->fmFimapFid)) {
            ZLog::Write(LOGLEVEL_DEBUG, sprintf("BackendIMAP->getFolderIdFromImapId('%s') IMAP cache folder not found, creating one", $imapid));
            $this->GetFolderList();
        }

        if ($case_sensitive) {
            if (isset($this->permanentStorage->fmFimapFid[$imapid])) {
                $folderid = $this->permanentStorage->fmFimapFid[$imapid];
                ZLog::Write(LOGLEVEL_DEBUG, sprintf("BackendIMAP->getFolderIdFromImapId('%s') = %s", $imapid, $folderid));
                return $folderid;
            }
            else {
                ZLog::Write(LOGLEVEL_DEBUG, sprintf("BackendIMAP->getFolderIdFromImapId('%s') = %s", $imapid, 'not found'));
                return false;
            }
        }
        else {
            if (isset($this->permanentStorage->fmFimapFidLowercase[strtolower($imapid)])) {
                $folderid = $this->permanentStorage->fmFimapFidLowercase[strtolower($imapid)];
                ZLog::Write(LOGLEVEL_DEBUG, sprintf("BackendIMAP->getFolderIdFromImapId('%s', false) = %s", $imapid, $folderid));
                return $folderid;
            }
            else {
                ZLog::Write(LOGLEVEL_DEBUG, sprintf("BackendIMAP->getFolderIdFromImapId('%s', false) = %s", $imapid, 'not found'));
                return false;
            }
        }

        ZLog::Write(LOGLEVEL_WARN, sprintf("BackendIMAP->getFolderIdFromImapId('%s') = %s", $imapid, 'not initialized!'));
        return false;
    }
```

**Comment by m-emelchenkov** [comment] 2015-11-08 14:33
@fmbiete 

```
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] -------- Start
08/11/2015 15:29:29 [12544] [ INFO] [email@example.com] Version='SVN-trunk-r1981' method='POST' from='x.x.x.x' cmd='SendMail' getUser='email@example.com' devId='xxxx' devType='iPhone'
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] Used timezone 'Europe/Amsterdam'
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] Including backend file: '/usr/local/share/z-push-contrib/backend/combined/combined.php'
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] Including backend file: '/usr/local/share/z-push-contrib/backend/imap/imap.php'
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] Combined 1 backends loaded.
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] Request::ProcessHeaders() ASVersion: 14.0
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] ZPush::CommandNeedsProvisioning(1): true
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] FileStateMachine->GetState() on file: '/var/lib/z-push/g/1/15llm4qfvt4gb8povcrt0ik81g-devicedata'
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] ASDevice data loaded for user: 'email@example.com'
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] TopCollector(): Initialized mutexid Resource id #17 and memid Resource id #18.
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] LoopDetection(): Initialized mutexid Resource id #20 and memid Resource id #21.
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] ZPush::HierarchyCommand(1): false
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] DeviceManager->ProvisioningRequired('xxxx') saved device key 'xxxx': false
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] ZPush::CommandNeedsAuthentication(1): true
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] Combined->Logon('email@example.com', '',***))
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->Logon(): User 'email@example.com' is authenticated on '{localhost:143/imap/notls/norsh}'
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] Combined->Logon() success
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] Combined->Setup('email@example.com', 'true', '')
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] Combined->Setup() success
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] ZPush::CommandNeedsPlainInput(1): false
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] StringStreamWrapper::Open(): len = 0
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] StringStreamWrapper::Open(): Using php://temp
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] StringStreamWrapper::Open(): len = 0
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] StringStreamWrapper::Open(): Using php://temp
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] Combined->SendMail()
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->SendMail(): RFC822: 386 bytes  forward-id: 'false' reply-id: 'false' parent-id: 'false' SaveInSent: 'empty' ReplaceMIME: 'false'
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->SendMail(): We get the new message
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->SendMail(): We get the From and To
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->getIdentityFromSql() - Connected to SQL Database
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->getIdentityFromSql() - Searching From with filter: select first_name, last_name, mail_address from users where mail_address = 'email@example.com'
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->getIdentityFromSql() - Found entry in SQL Database. Generating From
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->getFromHeaderValue(): from defined: email@example.com
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->getFromHeaderValue(): Overwriting From: =?UTF-8?B?xxxx==?= <email@example.com>
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->SendMail(): To defined: email@example.com
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->setReturnPathValue(): No Return-Path address defined, we use From
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->SendMail(): is a new message or we are replacing mime
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->addTextPartsMessage(): The message has plain body
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->SendMail(): Copying new headers
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->SendMail(): Final mail to send:
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->sendMessage(): SendingMail with mail
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->sendMessage(): send return value 1
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->saveSentMessage(): saving message in Sent Items folder
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] FileStateMachine->GetState() on file: '/var/lib/z-push/g/1/15llm4qfvt4gb8povcrt0ik81g-bs-1440013738'
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->getFolderIdFromImapId('SENT', false) = not found
08/11/2015 15:29:29 [12544] [ERROR] [email@example.com] BackendIMAP->saveSentMessage(): The email could not be saved to Sent Items folder. Check your configuration.
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] Flushing 0, headers already sent? no
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] Combined->Logoff()
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] BackendIMAP->close_connection(): disconnected from IMAP server
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] FileStateMachine->SetState() written 412 bytes on file: '/var/lib/z-push/g/1/15llm4qfvt4gb8povcrt0ik81g-bs-1440013738'
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] Combined->Logoff() success
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] LoopDetection->ProcessLoopDetectionTerminate()
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] Memory usage information: 1778912/2097152 - Execution time: 0.0491 - HTTP responde code: 200
08/11/2015 15:29:29 [12544] [DEBUG] [email@example.com] -------- End
```

**Comment by yodax** [comment] 2015-11-10 08:42
I'm affected by the same issue. Folder sent can't be found. It isn't a new mailbox. Folder exists and it worked previously. I tried matching the case in the configuration but no luck. 

If I can assist with debugging let me know

**Comment by m-emelchenkov** [comment] 2015-11-10 08:44
Don't know if it is related too, but: when I flagging a message, after refresh the flag disappears. The second time flagging works well. The same when I trying to enter Sent folder — first time I get error, the second time it opens OK.

**Comment by yodax** [comment] 2015-11-10 08:49
I hadn't noticed that, but I can confirm that happens.

**Comment by polytan02** [comment] 2015-11-15 18:04
Any news on this ?

**Comment by m-emelchenkov** [comment] 2015-11-30 22:25
Can't reproduce this issue after another enabling/disabling mail in iPhone and clearing /var/lib/z-push/*.

**Comment by cgiesche** [comment] 2015-12-25 11:55
As @m-emelchenkov already stated:
Removing everything from inside /var/lib/z-push/ fixes the problem. (Of course stop the webserver before that.)

**Comment by fmbiete** [comment] 2015-12-29 14:20
Yes, it's possible. Or maybe the z-push states files got corrupted. That would explain why I cannot reproduce it, since I'm using the SQL states...

I will close this, but it's not fixed, so please reopen it if it happens again.

**Closed by fmbiete** 2015-12-29 14:20 UTC
Labels: bug

**Comment by lilarcor** [comment] 2018-12-06 01:51
Removing everything from inside /var/lib/z-push/ fixes the problem, too.
