### ISSUE TITLE
 StatusException: SyncCollections->CheckForChanges(): Timeout forced after 0s fro  m 1680s due to other process - code: 3 - file: /usr/share/z-push/lib/core/synccollections.php:487

### ISSUE THREAD

**Issue by mardanx** [fmbiete/Z-Push-contrib#179] opened 2015-04-17 20:25 UTC
Hello,

Configured caldav, carddav, imap & searchldap with the latest source (pulled from git yesterday). 
Configured a Calendar, contacts and email on my android (5.1) device. All items sync, but I get a lot of timeout in the log. So I started experimenting. When I sync contacts no error, as soon I
enable the 2nd for sync, for example calendar I get the following log.

> 17/04/2015 21:56:49 [ 7410] [INFO] [***email***] Version='SVN-trunk-r1935' method='POST' from='***ip***' cmd='FolderSync' ge  tUser='***email***' devId='android1428850709769' devType='Android'
> 17/04/2015 21:56:49 [ 7410] [INFO] [***email***] ExportChangesDiff->InitializeExporter(): Found 7 changes
> 17/04/2015 21:56:49 [ 7410] [INFO] [***email***] ExportChangesDiff->InitializeExporter(): Found 0 changes
> 17/04/2015 21:56:49 [ 7410] [INFO] [***email***] ExportChangesDiff->InitializeExporter(): Found 0 changes
> 17/04/2015 21:56:50 [ 7410] [INFO] [***email***] Version='SVN-trunk-r1935' method='POST' from='***ip***' cmd='Sync' getUser=  '***email***' devId='android1428850709769' devType='Android'
> 17/04/2015 21:56:50 [ 7410] [INFO] [***email***] ExportChangesDiff->InitializeExporter(): Found 0 changes
> 17/04/2015 21:56:57 [ 7412] [INFO] [***email***] Version='SVN-trunk-r1935' method='POST' from='***ip***' cmd='FolderSync' ge  tUser='***email***' devId='android1428850709769' devType='Android'
> 17/04/2015 21:56:57 [ 7412] [INFO] [***email***] ExportChangesDiff->InitializeExporter(): Found 7 changes
> 17/04/2015 21:56:58 [ 7412] [INFO] [***email***] ExportChangesDiff->InitializeExporter(): Found 0 changes
> 17/04/2015 21:56:58 [ 7412] [INFO] [***email***] ExportChangesDiff->InitializeExporter(): Found 0 changes
> 17/04/2015 21:56:58 [ 7412] [INFO] [***email***] Version='SVN-trunk-r1935' method='POST' from='***ip***' cmd='Sync' getUser=  '***email***' devId='android1428850709769' devType='Android'
> 17/04/2015 21:56:59 [ 7412] [INFO] [***email***] ExportChangesDiff->InitializeExporter(): Found 0 changes
> 17/04/2015 21:56:59 [ 7412] [INFO] [***email***] Version='SVN-trunk-r1935' method='POST' from='***ip***' cmd='Sync' getUser=  '***email***' devId='android1428850709769' devType='Android'
> 17/04/2015 21:56:59 [ 7412] [INFO] [***email***] ExportChangesDiff->InitializeExporter(): Found 0 changes
> 17/04/2015 21:57:00 [ 7412] [INFO] [***email***] Version='SVN-trunk-r1935' method='POST' from='***ip***' cmd='Ping' getUser=  '***email***' devId='android1428850709769' devType='Android'
> 17/04/2015 21:57:00 [ 7412] [INFO] [***email***] SyncCollections->CheckForChanges(): Waiting for store changes... (lifetime 1680   seconds)
> 17/04/2015 21:57:00 [ 7412] [INFO] [***email***] StatusException: SyncCollections->CheckForChanges(): Timeout forced after 0s fro  m 1680s due to other process - code: 3 - file: /usr/share/z-push/lib/core/synccollections.php:487
> 17/04/2015 21:57:01 [ 7412] [INFO] [***email***] Version='SVN-trunk-r1935' method='POST' from='***ip***' cmd='Ping' getUser=  '***email***' devId='android1428850709769' devType='Android'
> 17/04/2015 21:57:01 [ 7412] [INFO] [***email***] SyncCollections->CheckForChanges(): Waiting for store changes... (lifetime 1680   seconds)
> 17/04/2015 21:57:01 [ 7412] [INFO] [***email***] StatusException: SyncCollections->CheckForChanges(): Timeout forced after 0s fro  m 1680s due to other process - code: 3 - file: /usr/share/z-push/lib/core/synccollections.php:487
> 17/04/2015 21:57:01 [ 7412] [INFO] [***email***] Version='SVN-trunk-r1935' method='POST' from='***ip***' cmd='Ping' getUser=  '***email***' devId='android1428850709769' devType='Android'

It looks like some connection get mixed up. Strange enough my android 4.4 simulator has no problems at all.

Regards,
Danny

**Comment by fmbiete** [comment] 2015-04-18 18:24
Did you try to restart the phone after enabling the sync for all 3 backends?? Maybe the EAS process is stucked in some point and retrying the command.

**Comment by mardanx** [comment] 2015-04-19 09:49
unfortunately it didn't help.

**Comment by mardanx** [comment] 2015-04-19 10:41
It looks like after installing some minor php/apache updates of my distro, the problem doesn't occur anymore.
Thank you for replying.

**Comment by fmbiete** [comment] 2015-04-20 15:03
ok, closing this as not a bug (at least in z-push)

**Closed by fmbiete** 2015-04-20 15:03 UTC
Labels: question

**Comment by jbonor** [comment] 2015-04-20 17:06
My installetion was running fine and after I have updated it to master the same error happens to me. What distro/php/apache were you running before and after?

**Comment by mardanx** [comment] 2015-04-20 17:44
Got ubuntu 12.04 running and upgraded apache 2  amd64 2.2.22-1ubuntu1.7 -> 2.2.22-1ubuntu1.8
php5:amd64 5.3.10-1ubuntu3.15 -> 5.3.10-1ubuntu3.17
